spring:
  profiles:
    active: dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mycloud.forservice.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
    name: mycloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.92.84:3306/mydatabase3
    username: root
    password: zwxzwx
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 10
      max-wait-millis: 1000
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: forservice-config-dept-client-8001
info:
  app.name: forservice-client-8001
  company.name: localhost
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mycloud.forservice.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: test
  application:
    name: mycloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.92.84:3306/mydatabase2
    username: root
    password: zwxzwx
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 10
      max-wait-millis: 1000
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: forservice-config-dept-client-8001
info:
  app.name: forservice-client-8001
  company.name: localhost
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  build.version: $project.version$